FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# El consumidor se ejecuta con python y tu script principal
CMD ["python", "run_consumer.py"]
